language: python
sudo: false
cache: false
python:
    - '3.6'
arch:
   - amd64
   - ppc64le

env:
  global:
    PYTHONUNBUFFERED=yes
  matrix:
    - TOXENV=2.7
    - TOXENV=3.7
    - TOXENV=3.6
    - TOXENV=3.5
    - TOXENV=pypy
    - TOXENV=pypy3
install: travis_retry pip install -U tox
script: tox -v -- -v
after_success:
  - .tox/$TRAVIS_PYTHON_VERSION/bin/coverage xml
  - .tox/$TRAVIS_PYTHON_VERSION/bin/codecov -e TOXENV
